In [1]:
import numpy as np


# 1.Arrays: 0-D, 1-D, 2-D, 3-D, 4-D.

## 0D array (scalar)

In [2]:
array_0d = np.array(42)
print("0D array:", array_0d)

0D array: 42


## 1d array (vector)

In [3]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", array_1d)

1D array: [1 2 3 4 5]


## 2D array (matrix)

In [4]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", array_2d)

2D array:
 [[1 2 3]
 [4 5 6]]


## 3D array (tensor)

In [5]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array:\n", array_3d)

3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 4D array

In [6]:
array_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print("4D array:\n", array_4d)


4D array:
 [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


# 2.Memory allocation

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print("Size of each element:", arr.itemsize)
print("Total bytes occupied:", arr.nbytes)

Size of each element: 8
Total bytes occupied: 40


# 3.Attributes of Array

In [8]:
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Dimension:", arr.ndim)

Shape: (5,)
Size: 5
Data Type: int64
Dimension: 1


# 4.Datatypes in NumPy

In [9]:
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1.5, 2.6, 3.1], dtype=np.float64)
arr_complex = np.array([1+2j, 3+4j])
arr_bool = np.array([True, False, True])

print(arr_int.dtype, arr_float.dtype, arr_complex.dtype, arr_bool.dtype)

int32 float64 complex128 bool


# 5.Interchange of Datatype in NumPy

In [10]:
arr = np.array([1, 2, 3, 4])
print("Before:", arr.dtype)
arr_float = arr.astype(np.float64) 
print("After:", arr_float.dtype)

Before: int64
After: float64


# 6.Array Manipulation: Flipping, Stacking, Joining

Flip along axis

In [11]:

arr = np.array([[1, 2], [3, 4]])
print(np.flip(arr))
print(np.flipud(arr))
print(np.fliplr(arr))


[[4 3]
 [2 1]]
[[3 4]
 [1 2]]
[[2 1]
 [4 3]]


Stacking

In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2))) 

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


Joining


In [13]:

print(np.concatenate((arr1, arr2)))

[1 2 3 4 5 6]


# 7.NumPy Arithmetic Operations: Elementwise, Scalar

In [14]:
arr = np.array([1, 2, 3, 4])
print(arr + 2)
print(arr * 2)  
print(arr + arr)  
print(arr * arr)  

[3 4 5 6]
[2 4 6 8]
[2 4 6 8]
[ 1  4  9 16]


# 8.Sorting in Array

In [15]:
arr = np.array([3, 1, 4, 1, 5, 9])
print(np.sort(arr))

[1 1 3 4 5 9]


# 9.Array Slicing

In [16]:

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[1:5])  
print(arr[:3])  
print(arr[-3:]) 

[2 3 4 5]
[1 2 3]
[4 5 6]


# 10.Array Filter

In [17]:
arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[arr > 25]  
print(filtered_arr)

[30 40 50]


# 11. Array Iteration

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for row in arr:
    for elem in row:
        print(elem, end=" ")

1 2 3 4 5 6 

# 12.Array Search

In [19]:
arr = np.array([10, 20, 30, 40, 50])
index = np.where(arr == 30)
print("Index of 30:", index)


Index of 30: (array([2]),)


# 13.Arrays with linspace()

In [20]:
arr = np.linspace(0, 10, 5)  
print(arr)

[ 0.   2.5  5.   7.5 10. ]


# 14.Types of Arrays: Zero array, one array, Full array, Eye array, Random number array, identity and diagonal array. 


## Zero array

In [21]:


zero_arr = np.zeros((3, 3))
print(zero_arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## one array

In [22]:
one_arr = np.ones((3, 3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Full array

In [23]:
full_arr = np.full((3, 3), 7)
print(full_arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]



## Eye array 


In [24]:
eye_arr = np.eye(3)
print("\nEye Array (Identity Matrix):\n", eye_arr)




Eye Array (Identity Matrix):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Random number array


In [25]:
rand_arr = np.random.rand(3, 3)
print("\nRandom Number Array:\n", rand_arr)




Random Number Array:
 [[0.24081735 0.80410653 0.17169066]
 [0.30040388 0.43355982 0.98199204]
 [0.31424882 0.06239453 0.26683101]]


## Identity array (same as eye)


In [26]:
identity_arr = np.identity(3)
print("\nIdentity Array:\n", identity_arr)





Identity Array:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Diagonal array


In [27]:
diag_arr = np.diag([1, 2, 3])
print("\nDiagonal Array:\n", diag_arr)


Diagonal Array:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
